export const videoPage = {
  linkCreationTitle: 'Создать короткую ссылку',
  timeCodeLabel: 'Начать с таймкода: ',
  fullScreenButton: 'На весь экран',
  fullScreenTooltip: 'Развернуть плеер на весь экран',
  shareButton: 'Поделиться',
  streamDateLabel: 'Дата стрима',
  streamSourceLabel: 'Источник стрима',
  recordSourceLabel: 'Источник записи',
  id: 'ID',
  streamId: 'ID стрима',
  youtube: 'YouTube',
  twitch: 'Twitch',
  torrent: 'Торрент',
  officialChannel: 'официальный канал',
  nonOfficialChannel: 'неофициальный канал',
  directLink: 'Прямая ссылка',
  downloadButton: 'Скачать',
  timecodesTitle: 'Таймкоды',
};
